name: Pytest Test Run with Allure Report

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout from branch
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.0"

    - name: Upgrade & Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt

    - name: Playwright Install
      run: python -m playwright install --with-deps

    - name: Run Tests UI
      run: pytest -v --screenshot=on -m "ui"

    - name: Run Tests API
      run: pytest -v --screenshot=on -m "api"


    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 30

